### ISSUE TITLE
Разобраться с загрузкой на Travis и Heroku

### ISSUE THREAD

**Issue by yana-chaputina** [yana-chaputina/Mc-web#1]

**Comment by coursar** [comment]
На тревисе так и не активировался репо?

**Comment by yana-chaputina** [comment]
![Screenshot_20191127_113736_com android chrome](https://user-images.githubusercontent.com/57296304/69707227-64666a00-110a-11ea-9d80-6ebd69cc4c6c.jpg)

**Comment by coursar** [comment]
вон же есть McDonalds-Web, попробуйте его включить

**Comment by coursar** [comment]
Надо на свитчер-то кликнуть

**Comment by yana-chaputina** [comment]
На тревисе все заработало. с heroku не очень понимаю,логи выглядят не так,как у вас в видео. в репозитории на гитхабе пакеты лежат версии 4.3, а я уже сделала коммит с версией 4.4, но ничего не обновилось,задеплоить не могу.
